import { SAMPLE_VIDEOS, getVideoThumbnail } from "@/lib/constants";
import ProfileHeader from "@/components/ProfileHeader";

export default function ProfilePage() {
  return (
    <div className="h-dvh pb-20 overflow-y-auto">
      <ProfileHeader
        username="coby"
        displayName="Coby"
        bio="Full-stack developer | Building cool stuff with Next.js & ImageKit"
        avatarPath="/default-image.jpg"
        stats={{ posts: 142000, followers: 28500, following: 890 }}
      />

      {/* Tabs */}
      <div className="flex border-b border-white/10">
        <button className="flex-1 py-3 text-center text-sm font-semibold border-b-2 border-white">
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="mx-auto">
            <rect x="3" y="3" width="7" height="7" />
            <rect x="14" y="3" width="7" height="7" />
            <rect x="14" y="14" width="7" height="7" />
            <rect x="3" y="14" width="7" height="7" />
          </svg>
        </button>
        <button className="flex-1 py-3 text-center text-sm text-white/40">
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="mx-auto">
            <path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z" />
          </svg>
        </button>
      </div>

      {/* Video thumbnail grid — thumbnails generated by ImageKit from video frames */}
      <div className="grid grid-cols-3 gap-0.5">
        {SAMPLE_VIDEOS.map((video) => (
          <div key={video.id} className="relative aspect-[9/16]">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={getVideoThumbnail(video.videoPath, video.thumbnailTime)}
              alt={video.description}
              className="w-full h-full object-cover"
            />
            {/* View count overlay */}
            <div className="absolute bottom-1 left-1 flex items-center gap-1">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="white">
                <polygon points="5 3 19 12 5 21 5 3" />
              </svg>
              <span className="text-xs font-semibold text-white drop-shadow">
                {Math.floor(Math.random() * 500 + 100)}K
              </span>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
